import React, { useEffect, useState } from 'react';
import { engineering } from '../api/engineering.api';
import { request } from '../api/client';
import MermaidDiagram from '../components/diagrams/MermaidDiagram';
import MockupRenderer from '../components/mockup-renderer/MockupRenderer';
import Modal from '../components/common/Modal';
import ImpactModal from '../components/common/ImpactModal';
import StatusBadge from '../components/common/StatusBadge';
import ModelEditor from '../components/ModelEditor';

const kinds = { Actor: 'Actores', UseCase: 'Casos de uso', Entity: 'Entidades', EntityAttribute: 'Atributos', EntityRelationship: 'Relaciones', BusinessRule: 'Reglas', NavigationNode: 'Navegación', Architecture: 'Arquitectura', Technology: 'Tecnologías' };
const diagramTypes = { ER_DIAGRAM: 'Entidad–relación', USE_CASE_DIAGRAM: 'Casos de uso', NAVIGATION_DIAGRAM: 'Navegación', SOFTWARE_ARCHITECTURE: 'Arquitectura de software', SYSTEM_ARCHITECTURE: 'Arquitectura del sistema' };
const examples = {
  Actor: { name: '', description: '' }, Entity: { name: '', description: '' }, BusinessRule: { name: '', description: '' },
  UseCase: { name: '', code: '', description: '', actorIds: [], relations: [] },
  EntityAttribute: { name: '', entityId: '', type: '', isPk: false },
  EntityRelationship: { name: '', source: '', target: '', cardinality: '', description: '' },
  NavigationNode: { name: '', route: '', platform: 'UNKNOWN', parentId: null, actorIds: [], useCaseIds: [] },
  Technology: { name: '', category: 'OTHER', version: null },
  Architecture: { name: '', kind: 'SOFTWARE_ARCHITECTURE', components: [], connections: [] }
};
const Json = ({ value }) => <pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', fontSize: 12 }}>{JSON.stringify(value, null, 2)}</pre>;
function download(name, content, type = 'application/json') { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

export default function ProjectEngineering({ project, view = 'modeling', onProjectUpdated }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [kind, setKind] = useState('Actor'), [editor, setEditor] = useState(null), [content, setContent] = useState(''), [reqIds, setReqIds] = useState([]);
  const [selected, setSelected] = useState(null), [rendered, setRendered] = useState(false), [change, setChange] = useState(null);
  const [baselineName, setBaselineName] = useState(''), [before, setBefore] = useState(''), [after, setAfter] = useState(''), [comparison, setComparison] = useState(null);
  const [message, setMessage] = useState(''), [chat, setChat] = useState(null), [proposeChange, setProposeChange] = useState(false), [provider, setProvider] = useState('local');
  const [sourceText, setSourceText] = useState('');
  const api = (path, body, method) => engineering(project.id, path, body, method);
  async function load() { setData(await api('')); }
  useEffect(() => { setSelected(null); setComparison(null); load().catch(e => setError(e.message)); }, [project.id, view]);
  async function run(fn) { setBusy(true); setError(''); try { const result = await fn(); await load(); await onProjectUpdated?.(); return result; } catch (e) { setError(e.message); } finally { setBusy(false); } }
  function openEditor(candidate) { setEditor(candidate || { kind }); setContent(JSON.stringify(candidate?.content || examples[kind], null, 2)); setReqIds(candidate?.requirementIds || []); }
  async function saveEditor() {
    await run(async () => { const parsed = JSON.parse(content); if (editor.id) await api(`/models/${editor.id}`, { content: parsed }, 'PATCH'); else await api('/models', { kind: editor.kind, name: parsed.name, content: parsed, requirementIds: reqIds, targetId: editor.targetId }); setEditor(null); });
  }
  function inspect(v) { setSelected(v); setRendered(false); }
  async function reviewVersion(status) { await run(async () => { await api(`/versions/${selected.id}`, { status, renderedSuccessfully: rendered }, 'PATCH'); setSelected(null); }); }
  function versions() { return (data?.Artifact || []).flatMap(a => a.versions.map(v => ({ ...v, label: `${diagramTypes[a.type] || 'Mockup'} · ${a.name} · v${v.version}`, category: 'Artifact' }))).concat((data?.requirementVersions || []).map(v => ({ ...v, label: `${v.content.code} · v${v.version}`, category: 'Requirement' })), (data?.baselines || []).map(v => ({ ...v, label: `Baseline ${v.name} · v${v.version}`, category: 'Baseline' }))); }
  if (!data) return <div className="page-scrollable">{error || 'Cargando ingeniería…'}</div>;
  const approvedReqs = data.Requirement.filter(r => r.status === 'APPROVED');
  const modelRows = kind === 'EntityAttribute' ? data.Entity.flatMap(e => e.attributes) : data[kind] || [];
  const artifactList = data.Artifact.filter(a => view === 'mockups' ? a.type === 'MOCKUP' : a.type !== 'MOCKUP');
  return <div className="page-scrollable" style={{ padding: 24, overflow: 'auto' }}>
    {error && <div role="alert" className="alert alert-danger">{error}</div>}
    {view === 'modeling' && <>
      <h2>Modelado pendiente</h2><p>Se genera exclusivamente desde requisitos aprobados. Revisa cada candidato antes de incorporarlo al modelo.</p>
      <div className="page-actions"><button className="btn btn-primary" disabled={busy || !approvedReqs.length} onClick={() => run(() => api('/models/generate', {}))}>Generar candidatos</button><button className="btn btn-outline" disabled={busy} onClick={() => openEditor()}>Crear candidato manual</button></div>
      <label>Sección <select className="form-control" value={kind} onChange={e => setKind(e.target.value)}>{Object.entries(kinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
      {data.candidates.filter(c => c.kind === kind).map(c => <article className="info-card" key={c.id} style={{ marginTop: 12 }}>
        <strong>{c.name}</strong> <StatusBadge status={c.status} /><p>{c.requirementIds.map(id => data.Requirement.find(r => r.id === id)?.code || id).join(', ')}</p>
        <details><summary>Contenido y evidencia</summary><Json value={c.content} /><Json value={c.evidence} /></details>
        {c.status === 'PENDING_REVIEW' && <div className="page-actions"><button className="btn btn-primary" disabled={busy} onClick={() => run(() => api(`/models/${c.id}`, { status: 'APPROVED' }, 'PATCH'))}>Aprobar</button><button className="btn btn-outline" onClick={() => openEditor(c)}>Editar</button><button className="btn btn-outline" disabled={busy} onClick={() => run(() => api(`/models/${c.id}`, { status: 'REJECTED' }, 'PATCH'))}>Rechazar</button></div>}
      </article>)}
      <h3>Modelo registrado</h3>{modelRows.map(row => <article className="info-card" key={row.id} style={{ marginTop: 8 }}><strong>{row.name || row.style || row.description}</strong> <StatusBadge status={row.status} /><small>{row.id}</small>{['PENDING_REVIEW', 'OUTDATED'].includes(row.status) && <button className="btn btn-outline" disabled={busy} onClick={() => { setEditor({ kind, targetId: row.id }); setReqIds(row.requirementIds.filter(id => approvedReqs.some(r => r.id === id))); setContent(JSON.stringify({ ...row, name: row.name || row.style || row.description }, null, 2)); }}>Revisar este modelo</button>}<details><summary>Datos</summary><Json value={row} /></details><button className="btn btn-outline" disabled={busy} onClick={() => { setEditor({ change: true, kind, row }); setContent(JSON.stringify(Object.fromEntries(Object.entries(row).filter(([k]) => ['name', 'description', 'route', 'platform', 'cardinality', 'type', 'style', 'version', 'category'].includes(k))), null, 2)); }}>Proponer cambio</button>{row.status === 'OUTDATED' && <button className="btn btn-outline" disabled={busy} onClick={() => run(() => api('/models/generate', { requirementIds: row.requirementIds }))}>Regenerar candidatos afectados</button>}</article>)}
    </>}
    {(view === 'diagrams' || view === 'mockups') && <>
      <h2>{view === 'diagrams' ? 'Diagramas Mermaid' : 'Mockups versionados'}</h2><p>Las versiones aprobadas se conservan. Cada generación produce una versión pendiente de revisión.</p>
      <div className="page-actions">{view === 'diagrams' ? Object.entries(diagramTypes).map(([type, label]) => <button className="btn btn-outline" key={type} disabled={busy} onClick={() => run(async () => inspect(await api('/diagrams', { type })))}>{label}</button>) : <button className="btn btn-primary" disabled={busy} onClick={() => run(() => request(`/projects/${project.id}/mockup`, { method: 'POST', body: {} }))}>Generar con n8n</button>}</div>
      <label>Plataforma confirmada <select className="form-control" value={data.project.platform} disabled={busy} onChange={e => run(() => api('/platform', { platform: e.target.value }, 'PATCH'))}>{['UNKNOWN', 'WEB', 'MOBILE', 'BOTH'].map(p => <option key={p}>{p}</option>)}</select></label><p>Detección desde requisitos: {data.detectedPlatform}</p>
      {artifactList.map(a => <article className="info-card" key={a.id} style={{ marginTop: 12 }}><strong>{diagramTypes[a.type] || a.versions[0]?.structuredContent.screen?.name || a.name}</strong> <StatusBadge status={a.status} /><p>Versión oficial: {a.versions.find(v => v.id === a.approvedVersionId)?.version || 'ninguna'}</p><button className="btn btn-outline" disabled={busy} onClick={() => run(() => a.type === 'MOCKUP' ? request(`/projects/${project.id}/mockup`, { method: 'POST', body: { artifactId: a.id } }) : api('/diagrams', { type: a.type, artifactId: a.id }))}>Regenerar este artefacto</button>{a.versions.map(v => <button className="btn btn-ghost" key={v.id} onClick={() => inspect(v)}>v{v.version} · {v.status}</button>)}</article>)}
    </>}
    {view === 'traceability' && <><h2>Matriz de trazabilidad</h2><p>Las ausencias se muestran para revisión; no se generan elementos para rellenarlas.</p><table style={{ width: '100%' }}><thead><tr><th>Requisito</th><th>Fuente</th><th>Modelos y artefactos</th><th>Sin cobertura</th></tr></thead><tbody>{data.matrix.map(row => <tr key={row.requirement.id}><td>{row.requirement.code}: {row.requirement.name}</td><td>{data.sources.find(s => s.id === row.evidence?.sourceId)?.name || 'Manual / sin fuente'}{row.evidence?.sourceSegmentId && <small>AudioSegment: {row.evidence.sourceSegmentId}</small>}</td><td>{row.coverage.map(c => <div key={c.id}>{c.type}: {data[c.type]?.find(x => x.id === c.id)?.name || c.id}</div>)}</td><td>{row.missing.join(', ') || 'Cubierto'}</td></tr>)}</tbody></table></>}
    {view === 'changes' && <><h2>Cambios</h2><p>Los cambios aprobados conservan versiones y marcan las dependencias OUTDATED.</p>
      {data.requirementCandidates.filter(c => c.status === 'PENDING_REVIEW' && c.evidence?.relationship?.requirementId).map(c => <article className="info-card" key={c.id}><strong>Posible {c.evidence.relationship.relation}: {c.evidence.relationship.target}</strong><p>{c.statement}</p><button className="btn btn-outline" disabled={busy} onClick={() => run(async () => setChange(await api('/changes', { type: 'UPDATE', elementType: 'Requirement', elementId: c.evidence.relationship.requirementId, proposedState: { description: c.statement }, sourceCandidateId: c.id, reason: 'Nueva evidencia: ' + c.title }))) }>Proponer cambio desde evidencia</button></article>)}
      {data.changes.map(c => <article className="info-card" key={c.id} style={{ marginTop: 12 }}><strong>{c.type}: {c.previousState.code || c.previousState.name || c.elementId}</strong> <StatusBadge status={c.status} /><p>{c.reason}</p><details><summary>Antes / propuesta / impacto</summary><Json value={c.previousState} /><Json value={c.proposedState} /><Json value={c.impact} /></details>{c.status === 'PENDING_APPROVAL' && <div className="page-actions"><button className="btn btn-primary" onClick={() => setChange(c)}>Revisar impacto</button><button className="btn btn-outline" disabled={busy} onClick={() => run(() => api(`/changes/${c.id}`, { status: 'REJECTED' }, 'PATCH'))}>Rechazar</button></div>}</article>)}</>}
    {view === 'versions' && <><h2>Historial, comparación y baselines</h2><div className="page-actions"><input className="form-control" placeholder="Nombre de baseline" value={baselineName} onChange={e => setBaselineName(e.target.value)} /><button className="btn btn-primary" disabled={busy || !baselineName.trim()} onClick={() => run(() => api('/baselines', { name: baselineName }))}>Crear baseline</button></div>
      <div className="page-actions"><select className="form-control" value={before} onChange={e => setBefore(e.target.value)}><option value="">Versión anterior</option>{versions().map(v => <option key={v.id} value={v.id}>{v.label}</option>)}</select><select className="form-control" value={after} onChange={e => setAfter(e.target.value)}><option value="">Versión posterior</option>{versions().map(v => <option key={v.id} value={v.id}>{v.label}</option>)}</select><button className="btn btn-outline" disabled={busy || !before || !after} onClick={() => run(async () => setComparison(await api('/compare', { before, after, type: versions().find(v => v.id === before)?.category })))}>Comparar</button></div>
      {comparison && <Json value={comparison} />}{versions().map(v => <article className="info-card" key={v.id}><strong>{v.label}</strong><details><summary>Consultar contenido</summary><Json value={v.content || v.structuredContent || v} /></details>{v.category !== 'Baseline' ? <button className="btn btn-outline" disabled={busy} onClick={() => run(async () => { if (v.category === 'Artifact') inspect(await api(`/versions/${v.id}/restore`, {})); else setChange(await api('/changes', { type: 'RESTORE', elementType: 'Requirement', elementId: v.requirementId, basedOnVersionId: v.id, reason: `Restaurar contenido v${v.version}` })); })}>Restaurar como nueva versión</button> : <button className="btn btn-outline" disabled={busy} onClick={() => run(async () => setComparison((await api(`/baselines/${v.id}`)).snapshot))}>Consultar snapshot</button>}</article>)}
      <button className="btn btn-outline" onClick={() => download(`${project.name}.json`, JSON.stringify(data, null, 2))}>Exportar JSON</button><button className="btn btn-outline" onClick={() => download(`${project.name}.md`, `# ${project.name}\n\n` + data.Requirement.map(r => `## ${r.code}: ${r.name}\n\n${r.description}\n\nEstado: ${r.status}`).join('\n\n'), 'text/markdown')}>Exportar Markdown</button>
    </>}
    {view === 'chat' && <><h2>Chat del proyecto</h2><p>Consulta evidencia e impacto. Para proponer un cambio, activa la revisión de candidatos.</p><textarea className="form-control" value={message} onChange={e => setMessage(e.target.value)} rows={4} /><label><input type="checkbox" checked={proposeChange} onChange={e => setProposeChange(e.target.checked)} /> Proponer cambio para revisión</label><select className="form-control" value={provider} onChange={e => setProvider(e.target.value)}><option value="local">Consulta local sin IA</option><option value="ollama">Ollama</option><option value="openai">GPT</option></select><button className="btn btn-primary" disabled={busy || !message.trim()} onClick={() => run(async () => setChat(await api('/chat', { message, proposeChange, provider })))}>Enviar</button>{chat && <><p>{chat.answer}</p><Json value={chat.context} /></>}<h3>Fuente manual</h3><textarea className="form-control" value={sourceText} onChange={e => setSourceText(e.target.value)} rows={4} /><button className="btn btn-outline" disabled={busy || !sourceText.trim()} onClick={() => run(async () => { await api('/sources/text', { text: sourceText, type: 'MANUAL' }); setSourceText(''); })}>Guardar fuente para analizar</button></>}
    <Modal isOpen={!!editor} onClose={() => setEditor(null)} title={editor?.change ? 'Proponer cambio controlado' : `Candidato: ${kinds[editor?.kind] || ''}`} footer={<button className="btn btn-primary" disabled={busy} onClick={editor?.change ? () => run(async () => { setChange(await api('/changes', { type: 'UPDATE', elementType: editor.kind, elementId: editor.row.id, proposedState: JSON.parse(content), reason: 'Edición manual del modelo' })); setEditor(null); }) : saveEditor}>Guardar propuesta</button>}>
      {!editor?.id && !editor?.change && <label>Requisitos aprobados (selección múltiple)<select multiple className="form-control" value={reqIds} onChange={e => setReqIds([...e.target.selectedOptions].map(o => o.value))}>{approvedReqs.map(r => <option key={r.id} value={r.id}>{r.code}: {r.name}</option>)}</select></label>}
      <p>Define únicamente datos confirmados. Deja sin especificar lo que aún no tenga evidencia.</p>{editor && <ModelEditor kind={editor.kind} value={content} onChange={setContent} data={data} targetId={editor.targetId || editor.row?.id} />}
    </Modal>
    <Modal isOpen={!!selected} onClose={() => setSelected(null)} title={`Versión ${selected?.version} · ${selected?.status}`} footer={<>{selected?.status === 'PENDING_REVIEW' && <><button className="btn btn-primary" disabled={busy || (!!selected.renderedContent && !rendered)} onClick={() => reviewVersion('APPROVED')}>Aprobar</button><button className="btn btn-outline" disabled={busy} onClick={() => reviewVersion('REJECTED')}>Rechazar</button></>}<button className="btn btn-outline" onClick={() => setSelected(null)}>Cerrar</button></>}>
      {selected?.renderedContent && <MermaidDiagram key={selected.id} code={selected.renderedContent} onValidated={(ok, err) => { setRendered(ok); if (!ok && selected.status === 'PENDING_REVIEW') run(async () => { await api(`/versions/${selected.id}`, { status: 'ERROR', error: err }, 'PATCH'); setSelected(v => ({ ...v, status: 'ERROR', technicalError: err })); }); }} />}
      {selected?.structuredContent.screen && (selected.structuredContent.screen.html ? <iframe title="Mockup candidato" sandbox="" srcDoc={selected.structuredContent.screen.html} style={{ width: '100%', height: 500, border: 0 }} /> : <MockupRenderer screen={selected.structuredContent.screen} />)}
      {selected?.technicalError && <p role="alert">{selected.technicalError}</p>}<details><summary>Modelo estructurado y código</summary><Json value={selected?.structuredContent} /><pre>{selected?.renderedContent}</pre></details>
    </Modal>
    <ImpactModal change={change} busy={busy} onClose={() => setChange(null)} onConfirm={() => run(async () => { await api(`/changes/${change.id}`, { status: 'APPROVED', confirmImpact: true }, 'PATCH'); setChange(null); })} />
  </div>;
}
